# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau22-recept-grupp2-yiqamvjp984a.reky.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Soppan vi testar",
    "description": "Riktigt god höstsoppa",
    "ratings": [],
    "imageUrl": "http://via.placeholder.com/640x360",
    "timeInMins": 40,
    "categories": [ "Förrätt", "Smaskigt" ],
    "instructions": [ "Koka grönsakerna", "Mixa med stavmixer", "Tillsätt vatten vid behov och mixa vidare"],
    "ingredients": [
        {
            "name": "Tomat",
            "amount": 2,
            "unit": "styck"
        },
        {
            "name": "Paprika",
            "amount": 150,
            "unit": "gram"
        },
        {
            "name": "Smör",
            "amount": 10,
            "unit": "gram"
        }
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Wok med glasnudlar",
    "description": "Wokade mungböngroddar med rostade jordnötter, strimlad bladselleri och glasnudlar. En vegansk wok som du snabbt fräser ihop!",
    "ratings": [2, 3, 3, 4, 1, 2, 5, 3, 2],
    "imageUrl": "https://cdn.pixabay.com/photo/2015/09/29/11/30/wok-963754_640.jpg",
    "timeInMins": 10,
    "categories": [ "Wok" ],
    "instructions": [ "Hetta upp olja i en wok eller stekpanna", "Fräs löken och lägg i groddar och selleri", "Blanda ner nudlarna och stek hastigt på hög värme", "Smaka av med salt och servera direkt"],
    "ingredients": [
        {
            "name": "Olja (jordnötsolja och solrosolja",
            "amount": 4,
            "unit": "msk"
        },
        {
            "name": "Salladslök",
            "amount": 4,
            "unit": "st"
        },
        {
            "name": "Mungbönsgroddar",
            "amount": 1,
            "unit": "dl"
        },
        {
            "name": "Bladselleri",
            "amount": 1,
            "unit": "dl"
        },
        {
            "name": "Risnudlar",
            "amount": 250,
            "unit": "gram"
        }
    ]
}

###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=toas HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/6513d48599612c970cb37a8e HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/65118ce699612c970cb379f8 HTTP/1.1
Content-Type: application/json

{
"ingredients": [
        {
            "name": "Bröd",
            "amount": 1,
            "unit": "skiva"
        },
        {
            "name": "Räkor",
            "amount": 75,
            "unit": "gram"
        },
        {
            "name": "Majonnäs",
            "amount": 2,
            "unit": "msk"
        },
        {
            "name": "Citron",
            "amount": 1,
            "unit": "skiva"
        }
    ]
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Förrätt/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=brus HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/632da30c6e7766b37d983811/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/632da30c6e7766b37d983811/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/65269c6899612c970cb6f6d2/comments
Content-Type: application/json

{
    "comment": "Förvirrad",
    "name": "Benjamin"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
